services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /mnt/swarm/VaultWarden/:/data/
    networks:
      traefik_proxy:
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vaultwarden.entrypoints=http"
        - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.themitthome.com`)"
        - "traefik.http.middlewares.vaultwarden-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.vaultwarden.middlewares=vaultwarden-https-redirect"
        - "traefik.http.routers.vaultwarden-secure.entrypoints=https"
        - "traefik.http.routers.vaultwarden-secure.rule=Host(`vaultwarden.themitthome.com`)"
        - "traefik.http.routers.vaultwarden-secure.tls=true"
        - "traefik.http.routers.vaultwarden-secure.service=vaultwarden"
        - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
        - "traefik.swarm.network=traefik_proxy"
    security_opt:
      - no-new-privileges:true

networks:
  traefik_proxy:
    external: true
