# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  cloudflared:
    # Restart on crashes and on reboots
    image: cloudflare/cloudflared:latest
    command: proxy-dns
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://9.9.9.9/dns-query,https://149.112.112.9/dns-query"

      # Listen on an unprivileged port
      - "TUNNEL_DNS_PORT=5053"

      # Listen on all interfaces
      - "TUNNEL_DNS_ADDRESS=0.0.0.0"

    # Attach cloudflared only to the private network
    networks:
      pihole_internal:
        ipv4_address: 172.70.9.153
    security_opt:
      - no-new-privileges:true
    deploy:
      replicas: 1

  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
#      - target: 53
#        published: 53
#        protocol: tcp
#        mode: ingress
#      - target: 53
#        published: 53
#        protocol: udp
#        mode: ingress
      - "53:53/udp"
    #  - "67:67/udp" DHCP - uncomment if using it
      - "500:80/tcp"
    #  - "443:443/tcp"
    networks:
      pihole_internal:
        ipv4_address: 172.70.9.152
      traefik_proxy:
    environment:
      TZ: 'US/Pacific'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password:
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'3
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: '172.70.9.3#5053'
    # Volumes store your data between container upgrades
    volumes:
      - '/mnt/swarm/pihole/:/etc/pihole/'
      - '/mnt/swarm/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    deploy:
      mode: replicated
      replicas: 1
networks:
  pihole_internal:
    external: true
  traefik_proxy:
    external: true
